### ISSUE TITLE
Encoder demos seem to be broken

### ISSUE THREAD

**Issue by czzarr** [gnovack/tinkerd#1]
Hello,
Thank you for writing your awesome series of blogposts, they're some of the best if not the best explanations I've read of embeddings and transformers.
However it seems that the demos on this page https://tinkerd.net/blog/machine-learning/bert-encoder/ are broken: they load inifinitely for me. I've tried on Chrome and Safari.
I'd be happy to provide more detail if you need.
I really hope you can fix them!

**Comment by czzarr** [comment]
seems like it's working again

**Comment by gnovack** [comment]
Hi @czzarr, thanks for the kind words! Sorry you were seeing issues with this page. 
To be honest. I'm not really sure what happened here. I've been running this site on free-tiers up to this point, and don't really have much visibility into issues like this.

Maybe it's time to start putting some monitoring in place.
